export enum CremationBookingStatusEnum {
  BOOKING_IN_PROGRESS = 'BOOKING_IN_PROGRESS',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  BACK_TO_FUNERAL_PARLOUR = 'BACK_TO_FUNERAL_PARLOUR',
  CREMATION_IN_PROGRESS = 'CREMATION_IN_PROGRESS',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  CORRECTION_NEEDED = 'CORRECTION_NEEDED',
  CORRECTION_COMPLETED = 'CORRECTION_COMPLETED',
  REJECTED = 'REJECTED'
}
